version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpa_frontend
    ports:
      - "8080:80"  # O el puerto que estés usando para el frontend
    networks:
      - backend-rpas-op-center_default
    restart: unless-stopped

networks:
  backend-rpas-op-center_default:
    external: true
