server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirección al contenedor del backend
    location /api/ {
        # 'rpa_backend' es el container_name de tu back
        # '8001' es el puerto interno del contenedor del back
        proxy_pass http://rpa_operations_app:8001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
